services:
  aroundhub_db:
    image: mariadb:10.6
    container_name: esop_db
    restart: always
    env-env_file:
      - ./env
    ports:
      - "3308:3306"
    volumes:
      - ./master_db/data:/var/lib/mysql
      - ./master_db/config/:/etc/mysql/conf.d
  aroundhub_redis:
    image: redis:7.0.0
    container_name: esop_redis
    restart: always
    ports:
      - "6381:6379"
